import { Code, Smartphone, Share2, TrendingUp, BarChart, Cloud, Database, Paintbrush, Server, Shield, ShoppingCart, Users, Video, Zap, FileText, Globe, Layers, Mic } from "lucide-react";


export const services = [
    {
      icon: Code,
      title: "Website Development",
      description: "Create stunning, responsive websites that drive results",
      features: [
        "Custom Web Applications",
        "E-commerce Solutions",
        "CMS Development",
        "Performance Optimization",
      ],
      urlLink: "/services/web-development",
    },
    {
      icon: Smartphone,
      title: "App Development",
      description: "Build powerful mobile applications for iOS and Android",
      features: [
        "Native App Development",
        "Cross-platform Solutions",
        "UI/UX Design",
        "App Maintenance",
      ],
      urlLink: "/services/app-development",
    },
    {
      icon: Share2,
      title: "Social Media Management",
      description: "Enhance your brand presence across social platforms",
      features: [
        "Content Strategy",
        "Community Management",
        "Social Media Analytics",
        "Engagement Optimization",
      ],
      urlLink: "/services/social-media-management",
    },
    {
      icon: TrendingUp,
      title: "Digital Marketing",
      description: "Drive growth with data-driven marketing strategies",
      features: [
        "SEO Optimization",
        "PPC Campaigns",
        "Content Marketing",
        "Analytics & Reporting",
      ],
      urlLink: "/services/digital-marketing",
    },
    {
      icon: Cloud,
      title: "Cloud Solutions",
      description: "Leverage cloud technology for scalable business operations",
      features: [
        "AWS & Azure Solutions",
        "Cloud Migration Services",
        "Serverless Applications",
        "Infrastructure Management",
      ],
      urlLink: "/services/cloud-solutions",
    },
    {
      icon: Database,
      title: "Database Management",
      description: "Efficient database solutions for robust applications",
      features: [
        "Database Design",
        "Optimization & Scaling",
        "Backup & Recovery",
        "Security Management",
      ],
      urlLink: "/services/database-management",
    },
    {
      icon: Shield,
      title: "Cybersecurity Services",
      description: "Protect your business with top-tier cybersecurity solutions",
      features: [
        "Risk Assessment",
        "Network Security",
        "Vulnerability Testing",
        "Data Encryption",
      ],
      urlLink: "/services/cybersecurity",
    },
    {
      icon: Paintbrush,
      title: "UI/UX Design",
      description: "Deliver engaging user experiences through design innovation",
      features: [
        "User Research",
        "Wireframing & Prototyping",
        "Custom Design Systems",
        "Interaction Design",
      ],
      urlLink: "/services/ui-ux-design",
    },
    {
      icon: Server,
      title: "DevOps Solutions",
      description: "Streamline software delivery through DevOps automation",
      features: [
        "CI/CD Pipeline Setup",
        "Infrastructure as Code",
        "Monitoring & Logging",
        "Performance Optimization",
      ],
      urlLink: "/services/devops-solutions",
    },
    {
      icon: BarChart,
      title: "Business Analytics",
      description: "Unlock insights with advanced data analysis",
      features: [
        "Data Visualization",
        "Predictive Analytics",
        "Dashboard Creation",
        "Reporting & Insights",
      ],
      urlLink: "/services/business-analytics",
    },
    {
      icon: Video,
      title: "Video Production",
      description: "Engage audiences with high-quality video content",
      features: [
        "Corporate Videos",
        "Product Demos",
        "Social Media Ads",
        "Post-production Editing",
      ],
      urlLink: "/services/video-production",
    },
    {
      icon: Users,
      title: "IT Consulting",
      description: "Drive digital transformation with expert IT consulting",
      features: [
        "Technology Assessment",
        "IT Roadmap Planning",
        "System Integration",
        "Process Automation",
      ],
      urlLink: "/services/it-consulting",
    },
    {
      icon: ShoppingCart,
      title: "E-Commerce Solutions",
      description: "Build seamless and scalable online shopping experiences",
      features: [
        "Custom E-commerce Platforms",
        "Payment Gateway Integration",
        "Inventory Management",
        "Multi-vendor Solutions",
      ],
      urlLink: "/services/e-commerce-solutions",
    },
    {
      icon: Zap,
      title: "Automation Solutions",
      description: "Enhance productivity with intelligent automation tools",
      features: [
        "Workflow Automation",
        "Robotic Process Automation (RPA)",
        "Task Scheduling",
        "AI-based Solutions",
      ],
      urlLink: "/services/automation-solutions",
    },
    {
      icon: Globe,
      title: "SEO & Content Strategy",
      description: "Improve your online visibility with strategic SEO and content planning",
      features: [
        "Keyword Research",
        "On-Page & Off-Page SEO",
        "Content Creation",
        "SEO Audits",
      ],
      urlLink: "/services/seo-content-strategy",
    },
    {
      icon: Mic,
      title: "Voice Technology Integration",
      description: "Integrate voice-enabled solutions for smart applications",
      features: [
        "Voice Assistant Integration",
        "Voice UI Development",
        "Speech Recognition",
        "Voice Command Features",
      ],
      urlLink: "/services/voice-technology",
    },
    {
      icon: FileText,
      title: "Technical Writing",
      description: "Deliver clear and precise technical documentation for your projects",
      features: [
        "User Manuals",
        "API Documentation",
        "Technical Guides",
        "Product Tutorials",
      ],
      urlLink: "/services/technical-writing",
    },
    {
      icon: Layers,
      title: "Product Design",
      description: "Transform ideas into functional, user-centered product designs",
      features: [
        "Wireframes & Mockups",
        "Interactive Prototypes",
        "Usability Testing",
        "End-to-End Design Solutions",
      ],
      urlLink: "/services/product-design",
    },
  ];